markdown: redcarpet
permalink: /:year/:i_month/:i_day/:title.html
exclude: [Rakefile, Gemfile, Gemfile.lock, README.markdown, Capfile, bin, tmp]
paginate: 3
gems: [jekyll-paginate]
#relative_permalinks: true

logo: /images/icon.jpg